launcher-config:
  alibaba-launcher:
    username: aliuser
    password: 123
    description: 'This is alibaba'
  tencent-launcher:
    username: tencentuser
    password: 456
    description: 'This is tencent'
  bytedance-launcher:
    username: bytedance
    password: 789
    description: 'This is bytedance'